### ISSUE TITLE
Improved battle mechanics

### ISSUE THREAD

**Issue by DIONYSUS-BASOUNAS** [achilleasmitos/text-adventure#49]
After the completion and implementation of #46, it's time for a more revised battle system

ACCEPTANCE CRITERIA:

1. The player and the foe should roll for initiative and the one with the higher number attacks first,
2. After the initiative roll, we should have an attack roll, the attack roll + strength should be higher than the AC of the enemy for the attack to continue
3. The Battle should effect the players and the foes hp, and determine the winner when the hp for one of the two is 0
4. If the players has 0 hp, then a death save throw should begin, on the failed attempts  the game should end  
5. The player should have the ability to flee (optional)

**Comment by achilleasmitos** [comment]
Perhaps we should consider implementing a "free player choice" that will allow the player to flee the battle. By "free", I mean that the player can write anything they want as an answer to what they want to do (eg: attack, use item, flee...) and the game responds to that. It would be a separate issue, though.
