### ISSUE TITLE
Text speed set in LoadingScreen gets overriden by savefile

### ISSUE THREAD

**Issue by achilleasmitos** [achilleasmitos/text-adventure#51]
During the loading screen of the game, the user is prompted to enter the speed of the text that they would like to have. However, this is immediately overwritten by the loading of the settings. This needs to be fixed.

### EXPECTED:
- The setting of the text speed should be moved away from the loading screen and be the first thing that happens upon StartGame
- No such choice exists for ContinueGame
- When the player selects StartGame and sets their preferred text speed, this should be immediately applied to the current game session
- When the player selects ContinueGame, the already-stored text speed should be used

**Comment by DIONYSUS-BASOUNAS** [comment]
i think we should not have the text speed in the loading screen and it should be moved to Start game, it doen't make sense to be on the loading screen and every time you open the game to have to select a text speed even if you play every day, it becomes tedious

**Comment by achilleasmitos** [comment]
> i think we should not have the text speed in the loading screen and it should be moved to Start game, it doen't make sense to be on the loading screen and every time you open the game to have to select a text speed even if you play every day, it becomes tedious

You are correct. I have modified the expected behavior to reflect that.
